kind: Deployment
apiVersion: apps/v1
metadata:
  name: zigbee2mqtt-switches
  namespace: home-automation
  uid: 0fa9a245-c027-412d-bc7e-150bb0671a32
  generation: 1
  labels:
    app.kubernetes.io/instance: zigbee2mqtt-switches
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zigbee2mqtt-switches
    helm.sh/chart: app-template-1.3.2
    helm.toolkit.fluxcd.io/name: zigbee2mqtt-switches
    helm.toolkit.fluxcd.io/namespace: home-automation
  annotations:
    deployment.kubernetes.io/revision: '1'
    meta.helm.sh/release-name: zigbee2mqtt-switches
    meta.helm.sh/release-namespace: home-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: zigbee2mqtt-switches
      app.kubernetes.io/name: zigbee2mqtt-switches
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: zigbee2mqtt-switches
        app.kubernetes.io/name: zigbee2mqtt-switches
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: z2m-switches-data
        - name: usb
          hostPath:
            path: /dev/serial/by-id/
            type: Directory
      containers:
        - name: zigbee2mqtt-switches
          image: docker.io/koenkk/zigbee2mqtt:1.40.0
          ports:
            - name: http
              containerPort: 8099
              protocol: TCP
          env:
            - name: ZIGBEE2MQTT_DATA
              value: /data
          resources:
            limits:
              memory: 4417M
            requests:
              cpu: 126m
              memory: 411M
          volumeMounts:
            - name: data
              mountPath: /data
            - name: usb
              mountPath: /dev/serial/by-id/
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      automountServiceAccountToken: true
      securityContext: {}
      schedulerName: default-scheduler
      enableServiceLinks: true
  strategy:
    type: Recreate
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600

